### ISSUE TITLE
omocodia

### ISSUE THREAD

**Issue by paolodina** [facciocose/django-italian-utils#1]
L'espressione regolare per l'omocodia dovrebbe essere:

```
[A-Za-z]{6}[0-9LMNPQRSTUV]{2}[A-Za-z]{1}[0-9LMNPQRSTUV]{2}[A-Za-z]{1}[0-9LMNPQRSTUV]{3}[A-Za-z]{1}
```

Vedi "Persone fisiche con identica espressione alfanumerica (omocodia)"  http://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Home/CosaDeviFare/Richiedere/Codice+fiscale+e+tessera+sanitaria/Richiesta+TS_CF/SchedaI/Informazioni+codificazione+pf/

**Comment by paolodina** [comment]
Inoltre mettendo un $ alla fine si può limitare il numero dei caratteri a 16.

**Comment by facciocose** [comment]
Ho aggiornato il validatore e scritto un test per un codice fiscale omocodico.

Adesso non dovrebbero esserci più problemi.
